spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://suleiman.db.elephantsql.com/achemjtt"
    username: achemjtt
    password: XBEqepxRWEC-d5TxK1RMnTGZFtuJmzxn
    hikari:
      maximum-pool-size: 1
  security:
    user:
      name: wolfcito
      password: wolfcito1234
